title: coolape.ca
author: APE G
email: 
description: >-
  13 year old artist creating and experimenting with NFTs

social:
  twitter: 
  facebook: 
  instagram: 
  github: 
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
